_primary: &primary
  adapter: postgres
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>

_statistics: &statistics
  adapter: postgres
  url: <%= ENV['TIMESCALE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  schema_dump: false
  migrations_paths:
    - db/statistics_migrate

development:
  primary:
    <<: *primary
  statistics:
    <<: *statistics

test:
  primary:
    <<: *primary
    url: <%= ENV['DATABASE_URL'] + '_test' %>
  statistics:
    <<: *statistics
    url: <%= ENV['TIMESCALE_URL'] + '_test' %>

staging:
  primary:
    <<: *primary
  statistics:
    <<: *statistics

production:
  primary:
    <<: *primary
  statistics:
    <<: *statistics
