:schedule:
  sync_all_contracts_from_esi:
    cron: '*/3 * * * *'
    class: 'Corporation::SyncAllContractsFromESIWorker'
    description: "Sync contracts for all corporations with contract sync enabled"

  sync_all_market_orders_from_esi:
    cron: '*/3 * * * *'
    class: 'MarketOrderSnapshot::SyncAllLocationsFromESIWorker'
    description: "Sync market orders for all regions/structures with market order sync enabled"

  sync_industry_indices_from_esi:
    cron: '0 * * * *'
    class: 'IndustryIndexSnapshot::SyncFromESIWorker'
    description: "Create a snapshot of industry indices"

  sync_market_prices_from_esi:
    cron: '0 * * * *'
    class: 'MarketPriceSnapshot::SyncFromESIWorker'
    description: "Create a snapshot of market prices"
