:schedule:
  sync_all_contracts_from_esi:
    cron: '*/5 * * * *'
    class: 'Corporation::SyncAllContractsFromESIWorker'
    description: "Sync contracts for all corporations with contract sync enabled"

  import_all_killmails_from_zkb:
    cron: '*/5 * * * *'
    class: 'Alliance::FetchAllKillmailsFromZKBWorker'
    description: "Import killmails for all alliances with killmail sync enabled"

  import_all_market_orders_from_esi:
    cron: '*/5 * * * *'
    class: 'MarketOrderSnapshot::FetchAllFromESIWorker'
    description: "Import market orders for all regions/structures with market order sync enabled"

  sync_industry_indices_from_esi:
    cron: '0 * * * *'
    class: 'IndustryIndexSnapshot::SyncFromESIWorker'
    description: "Create a snapshot of industry indices"

  sync_market_prices_from_esi:
    cron: '0 * * * *'
    class: 'MarketPriceSnapshot::SyncFromESIWorker'
    description: "Create a snapshot of market prices"

  create_market_fitting_snapshots:
    cron: '*/15 * * * *'
    class: 'MarketFittingSnapshot::CreateForAllFittingsAndMarkets'
    description: "Create snapshots for all markets/fittings"
