production: &production
  url: <%= ENV.fetch("DATA_REDIS_URL", "redis://127.0.0.1:6377/2") %>
  timeout: 1

development: &development
  url: <%= ENV.fetch("DATA_REDIS_URL", "redis://127.0.0.1:6377/2") %>
  timeout: 1

test:
  <<: *development
